/**
 * conversation-title.js - warm, after-the-fact titles for past Riley conversations (P2.3).
 *
 * Instead of showing a raw first line ("hey riley") in the conversation list, Riley names each
 * past conversation warmly and specifically ("The night we talked about your partner",
 * "Picking back up"). Titles are generated by the UTILITY model (Haiku, cheap + non-blocking)
 * AFTER the conversation, from its first several messages, and are member-editable.
 *
 * Storage: public.conversation_titles, keyed by (user_id, session_id), with a title_edited flag
 * so a member's own rename is NEVER auto-overwritten by a later regeneration (migration 095).
 *
 * SECURITY: identity comes from the verified access token ONLY (getUserIdFromToken) - never a
 * client-supplied user_id (that would be an IDOR). Every read/write is scoped to that user, and
 * generation only reads messages the caller actually owns.
 *
 * POST { token, action, ... }
 *   action "list"     { session_ids?: string[] }  -> { titles: { [session_id]: {title, edited} } }
 *   action "generate" { session_id }              -> { ok, title? , skipped? }  (fire-and-forget safe)
 *   action "rename"   { session_id, title }       -> { ok, title }              (sets title_edited=true)
 *
 * Fail-open: a titling failure NEVER breaks the conversation list. On any error the caller simply
 * falls back to the current first-line preview. Utility model + all DB writes are non-fatal.
 */

const { getSupabaseClient, getUserIdFromToken } = require("./supabase-client");
const { callClaude } = require("./anthropic-client");
const { MODELS } = require("./model-router");

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type, Accept",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const json = (c, o) => ({ statusCode: c, headers: { ...CORS, "Content-Type": "application/json" }, body: JSON.stringify(o) });

const MAX_TITLE_LEN = 60;   // hard storage cap (the model is asked for <= 6 words; this is a backstop)

// Riley's voice, plain hyphens, no quotes, never "hey riley". Warm + specific, not a summary.
const TITLE_SYSTEM = `You are Riley. You are looking back at one of your past conversations with a member and giving it a short, warm title - the way you'd name a memory you shared, not a subject line.

Return ONLY the title text. No quotes, no punctuation at the end, no preamble, no explanation.

RULES:
- 6 words MAX. Shorter is better. Often 2-4 words.
- Warm and human, in Riley's voice - like naming a moment you went through together.
- Specific to what THIS conversation was actually about when you can be (a person, a feeling, a turning point, a hard night, a small win). If it was just a light check-in or hello, a gentle human title is fine ("Checking in", "Picking back up", "A quiet night").
- Plain hyphens only ("-"). Never an em-dash or en-dash.
- NEVER echo the raw first message. NEVER return "hey riley" or any literal greeting.
- No emojis. No hashtags. No quotation marks. No trailing period.
- Never clinical, never a label, never diagnose. Never use the member's name unless it makes the title warmer and it's clearly theirs.
- If someone was grieving, struggling, or in crisis, keep the title gentle and caring - never stark.

Good examples (for shape, do not reuse verbatim):
The night we talked about your dad
Picking back up
When the cravings hit
A hard morning
Finding your footing
Talking through the breakup
Just checking in`;

// Fallback title from the first user line if the model is unavailable - still better than a raw
// echo: trims, strips a leading greeting, caps length. Never returns an empty string.
function fallbackTitle(firstUserText) {
  let t = String(firstUserText || "").replace(/\s+/g, " ").trim();
  // Strip a leading greeting so we never surface "hey riley ..." as the title.
  t = t.replace(/^(hey|hi|hello|yo|hey there|hi there)[\s,!.-]*riley[\s,!.-]*/i, "").trim();
  t = t.replace(/^(hey|hi|hello)[\s,!.-]+/i, "").trim();
  if (!t) return "A conversation with Riley";
  if (t.length > MAX_TITLE_LEN) t = t.slice(0, MAX_TITLE_LEN).replace(/\s+\S*$/, "").trim() || t.slice(0, MAX_TITLE_LEN).trim();
  // Sentence-case the first character; leave the rest as the member wrote it.
  return t.charAt(0).toUpperCase() + t.slice(1);
}

// Sanitize the model's output into a safe, on-brand title. Never throws.
function cleanTitle(raw) {
  let t = String(raw || "").trim();
  // Drop wrapping quotes / stray markdown / a leading label the model sometimes adds.
  t = t.replace(/^["'`\s]+|["'`\s]+$/g, "");
  t = t.replace(/^(title|conversation)\s*[:\-]\s*/i, "");
  t = t.split(/\r?\n/)[0].trim();          // first line only
  t = t.replace(/[‒–—―]/g, "-");  // any dash variant -> plain hyphen
  t = t.replace(/["""'']/g, "");            // smart quotes out
  t = t.replace(/[.\s]+$/g, "").trim();     // no trailing period/space
  if (t.length > MAX_TITLE_LEN) t = t.slice(0, MAX_TITLE_LEN).replace(/\s+\S*$/, "").trim() || t.slice(0, MAX_TITLE_LEN).trim();
  // Guard against the model echoing a bare greeting.
  if (/^(hey|hi|hello)\b/i.test(t) && /riley/i.test(t) && t.split(/\s+/).length <= 3) return "";
  return t;
}

exports.handler = async function (event) {
  if (event.httpMethod === "OPTIONS") return { statusCode: 204, headers: CORS, body: "" };
  if (event.httpMethod !== "POST") return json(405, { error: "Method not allowed" });

  let body;
  try { body = JSON.parse(event.body || "{}"); } catch { return json(400, { error: "Bad JSON" }); }

  let sb;
  try { sb = getSupabaseClient(); } catch (_) { return json(500, { error: "config" }); }

  const userId = await getUserIdFromToken(sb, body.token);
  if (!userId) return json(401, { error: "Unauthorized" });

  const action = body.action || "list";

  try {
    // ── LIST: stored titles for the given sessions (or all of the member's). One call powers the
    // whole list render; the page then only fires "generate" for sessions with no title yet. ──
    if (action === "list") {
      let q = sb.from("conversation_titles").select("session_id,title,title_edited").eq("user_id", userId);
      if (Array.isArray(body.session_ids) && body.session_ids.length) {
        q = q.in("session_id", body.session_ids.slice(0, 400).map(String));
      }
      const { data } = await q.limit(500);
      const titles = {};
      (data || []).forEach((r) => { titles[r.session_id] = { title: r.title, edited: !!r.title_edited }; });
      return json(200, { titles });
    }

    // ── RENAME: the member edited the title. Upsert with title_edited=true so the generator never
    // overwrites it again. IDOR-safe: scoped to (user_id, session_id). ──
    if (action === "rename") {
      const sessionId = String(body.session_id || "").trim();
      let title = String(body.title || "").replace(/\s+/g, " ").trim();
      if (!sessionId) return json(400, { error: "session_id required" });
      if (title.length < 1) return json(400, { error: "title required" });
      title = title.replace(/[‒–—―]/g, "-").slice(0, MAX_TITLE_LEN).trim();
      const now = new Date().toISOString();
      const { error } = await sb.from("conversation_titles").upsert(
        { user_id: userId, session_id: sessionId, title, title_edited: true, updated_at: now },
        { onConflict: "user_id,session_id" }
      );
      if (error) { console.warn("[conversation-title] rename upsert failed:", error.message); return json(500, { error: "save failed" }); }
      return json(200, { ok: true, title });
    }

    // ── GENERATE: warm title for one untitled session. Idempotent + fire-and-forget safe:
    // never regenerates a member-edited title, and never touches another user's data. ──
    if (action === "generate") {
      const sessionId = String(body.session_id || "").trim();
      if (!sessionId) return json(400, { error: "session_id required" });

      // Already titled? Respect an edited title always; skip regenerating an existing auto title too
      // (titles are stable - a conversation's meaning doesn't change after the fact).
      const { data: existing } = await sb.from("conversation_titles")
        .select("title,title_edited").eq("user_id", userId).eq("session_id", sessionId).maybeSingle();
      if (existing && existing.title) {
        return json(200, { ok: true, skipped: true, title: existing.title, edited: !!existing.title_edited });
      }

      // Read the first several messages of THIS session that the caller owns (IDOR-scoped).
      const { data: msgs } = await sb.from("riley_conversations")
        .select("role,content,created_at")
        .eq("user_id", userId).eq("session_id", sessionId)
        .order("created_at", { ascending: true }).limit(8);
      if (!msgs || !msgs.length) return json(200, { ok: true, skipped: true, reason: "no messages" });

      const firstUser = (msgs.find((m) => m.role === "user") || {}).content || msgs[0].content || "";
      const transcript = msgs
        .map((m) => `${m.role === "user" ? "Person" : "Riley"}: ${String(m.content || "").slice(0, 400)}`)
        .join("\n")
        .slice(0, 2500);

      // Utility model (Haiku) via the shared client - non-blocking, cost-logged, fail-open. A low
      // temperature keeps titles calm and consistent. On ANY failure we fall back to a cleaned first line.
      let title = "";
      try {
        const r = await callClaude({
          system: TITLE_SYSTEM,
          messages: [{ role: "user", content: `Here is the start of the conversation. Give it its warm title.\n\n${transcript}` }],
          max_tokens: 24,
          temperature: 0.5,
          model: MODELS.utility,
          functionName: "conversation-title",
          userId,
          supabase: sb,
        });
        title = cleanTitle(r.text || "");
      } catch (e) {
        console.warn("[conversation-title] generate model call failed (fail-open to first line):", e.message);
      }
      if (!title) title = fallbackTitle(firstUser);

      const now = new Date().toISOString();
      // Only write if still untitled and not member-edited (double-check guards a race between two
      // list renders firing generate for the same session). onConflict keeps title_edited intact.
      const { data: recheck } = await sb.from("conversation_titles")
        .select("title,title_edited").eq("user_id", userId).eq("session_id", sessionId).maybeSingle();
      if (recheck && (recheck.title_edited || recheck.title)) {
        return json(200, { ok: true, skipped: true, title: recheck.title, edited: !!recheck.title_edited });
      }
      const { error } = await sb.from("conversation_titles").upsert(
        { user_id: userId, session_id: sessionId, title, title_edited: false, updated_at: now },
        { onConflict: "user_id,session_id" }
      );
      if (error) { console.warn("[conversation-title] generate upsert failed (non-fatal):", error.message); return json(200, { ok: false, title }); }
      return json(200, { ok: true, title });
    }

    return json(400, { error: "unknown action" });
  } catch (e) {
    console.error("[conversation-title]", e.message);
    return json(500, { error: "server" });
  }
};
