-- 053_program_seed.sql — self-guided program content (Sobriety/Grief/Body), parsed from the briefs.
-- Run AFTER 051. Idempotent: clears + reinserts these 3 programs' modules.
DELETE FROM program_modules WHERE program_key IN ('prog_sobriety','prog_grief','prog_body');
INSERT INTO program_modules
  (program_key, module_number, part_number, part_title, title, read_body, do_body, keep_title, keep_body, riley_layer, safety_footer)
VALUES
('prog_sobriety', 1, 1, $x$UNDERSTAND IT$x$, $x$Start Where You Are$x$, $x$No rock bottom required. The spectrum from "drinking more than I'd like" to "I can't stop" — and why the same tools serve the whole spectrum. You define the goal: less, none, or "I don't know yet" (all three are legitimate starting points).$x$, $x$The honest audit — one week's actual intake written down, no rounding down, nobody sees it.$x$, NULL, NULL, $x$Riley layer: Riley asks what the number on the page made them feel — and says, whatever it was, "that number took courage to write."$x$, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 2, 1, $x$UNDERSTAND IT$x$, $x$What It's Actually Doing$x$, $x$Plain-language neuroscience. Dopamine, tolerance, and the hijacked reward loop — why "just have willpower" is like telling someone to out-argue their own brain chemistry. Why it worked (it did a job: quieting, numbing, socializing) and why it stopped working.$x$, $x$Finish this sentence in writing: "The job the drink was doing for me was ______."$x$, NULL, NULL, $x$Riley layer: Riley remembers this sentence permanently — it becomes the reference point for Modules 7 and 12.$x$, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 3, 1, $x$UNDERSTAND IT$x$, $x$The Craving, Decoded$x$, $x$A craving is a wave, not a command — it rises, peaks (typically within 15–20 minutes), and falls whether or not you act on it. HALT (Hungry, Angry, Lonely, Tired): most cravings are one of these four wearing a costume. Blood sugar dips that impersonate cravings.$x$, $x$Next craving — don't fight it, just time it. Note when it started and when it faded. Data, not battle.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 4, 1, $x$UNDERSTAND IT$x$, $x$The Emergency Craving Protocol$x$, $x$Short — why a pre-decided plan beats in-the-moment willpower every time (the deciding must happen before the wave, not during).$x$, $x$Copy the protocol somewhere you'll actually find it at 9pm on a Friday — phone notes, wallet card, bathroom mirror.$x$, $x$The Emergency Craving Protocol$x$, $x$**THE PROTOCOL (print it, save it, pocket it):**
1. **Name it out loud:** "This is a craving. It peaks in 20 minutes. It always passes."
2. **Move your body for 8 minutes.** Walk, stairs, push-ups against the counter — the fastest chemical interrupt there is. (Body Rebuild's 8-Minute Reset workout pairs here.)
3. **Cold water** — a glass down, and some on your face or wrists. Vagus-nerve brake.
4. **Eat something with protein.** Half the wave is often blood sugar.
5. **Text one person or write one paragraph.** The craving loses power the moment it's witnessed.
6. **Set a 20-minute timer.** Your only job is to be on the other side of it. Not forever — 20 minutes.$x$, $x$Riley layer (Coach): craving mentioned in chat → Riley runs the protocol steps live, and proactively checks in 25 minutes later.$x$, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 5, 2, $x$SURVIVE IT$x$, $x$Your Triggers, Mapped$x$, $x$Triggers aren't weaknesses; they're calendar entries. People, places, times, feelings — the Friday drive home, the brother-in-law, the 9pm kitchen. Mapping them converts ambushes into appointments you can plan for.$x$, $x$The map — four columns (people / places / times / feelings), five entries each. Then star the ONE that shows up most.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 6, 2, $x$SURVIVE IT$x$, $x$The First Two Weeks, In the Body$x$, $x$What's physically coming so nothing surprises you: sleep weirdness (vivid dreams, 3am wakeups), sugar cravings (the brain hunting its dopamine elsewhere), irritability, fatigue — all normal, all temporary, most peaking inside two weeks. When it's more than uncomfortable: the honest section on medical detox — if you drink daily and heavily, stopping cold can be dangerous; talk to a doctor first. No shame, just physiology.$x$, $x$Stock the counter-moves tonight: protein snacks, something sweet that isn't a drink, a boring bedtime plan.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 7, 2, $x$SURVIVE IT$x$, $x$Replacing the Ritual$x$, $x$The drink had a time slot and a job (Module 2's sentence). Empty time slots refill themselves with the old tenant unless something new signs the lease. The replacement must serve the same job — if the drink was "off-switch," the replacement must actually switch you off.$x$, $x$Design the new ritual for your #1 trigger slot — specific, same time, starts this week.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 8, 2, $x$SURVIVE IT$x$, $x$The Slip & Relapse Response Protocol$x$, $x$The most dangerous moment isn't the slip — it's the hour after, when "I blew it" becomes "so why stop now." The abstinence-violation trap, disarmed in advance.$x$, $x$Read the protocol once now, while you don't need it. That's the whole assignment.$x$, $x$The Slip & Relapse Response Protocol$x$, $x$**THE PROTOCOL:**
1. **Stop the count-up, not the clock.** A slip is a data point, not a deletion of everything before it. The days you had still happened; the body-repair still happened.
2. **No inventory tonight.** No life-audit at 11pm. Water, food, sleep. The review happens tomorrow, in daylight.
3. **Tomorrow, ask three questions (on paper):** What was the situation? What was I feeling an hour before? What would I tell a friend who did exactly this?
4. **Find the gap in the map.** A slip almost always reveals a trigger Module 5 missed. Add it. The map just got better.
5. **Tell one person, or write it to yourself.** Secrets metastasize. Witnessed slips end; hidden ones continue.
6. **Resume. Not restart — resume.** Same tools, same rituals, next day. The program never expelled you.$x$, $x$Riley layer: a slip disclosed in chat triggers this protocol in Riley's voice — leading with care, never disappointment, per Care Principles.$x$, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 9, 2, $x$SURVIVE IT$x$, $x$The Emotional Backlog$x$, $x$Numbing was non-selective — it muted everything. Weeks in, the feelings come back online, including the ones the drinking was hired to handle. Crying at commercials, sudden anger, old grief surfacing: not breaking down, thawing out. What to do with feelings you haven't felt at full volume in years (the Worry Dump from the Reset works here; so does Module 3's wave-logic — feelings crest and pass too).$x$, $x$Five minutes, one page: "What I might have been avoiding feeling is ______." No fixing, just naming.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 10, 3, $x$STEADY IT$x$, $x$Telling People (Scripts Included)$x$, $x$You don't owe anyone your story. Three tiers of disclosure, with word-for-word scripts: the deflect ("I'm off it for now, feeling great"), the honest-lite ("I'm taking a break — it stopped working for me"), the real one (for the inner circle). Handling the pusher ("come on, one won't hurt") without a scene: the broken-record technique.$x$, $x$Pick your script for the next event on your calendar. Say it out loud twice.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 11, 3, $x$STEADY IT$x$, $x$Social Life, Rebuilt$x$, $x$The bar question ("what do you even order?") — answered: the standing drink order (soda-lime, NA beer, whatever occupies the hand). Arriving late, leaving early, the exit line pre-loaded. The harder truth: some friendships were drinking arrangements wearing friendship costumes — and the grief of that is real (the Grief program's Module 7 covers losses that aren't deaths; they pair well).$x$, $x$One social thing this week with your standing order and your exit line ready. Attendance is the win.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 12, 3, $x$STEADY IT$x$, $x$The Boredom Problem$x$, $x$Early sobriety's dirty secret: it can be boring. The drink compressed reward into one lever; now reward must be rebuilt wide — and dopamine recovers on its own timeline (weeks to months; anhedonia early on is chemistry, not your personality). Revisit Module 2's job-sentence: what did you love before the lever?$x$, $x$The list of ten — things you did at some point in life that cost nothing and required no drink. Do the easiest one this week.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 13, 4, $x$BECOME IT$x$, $x$The Identity Question$x$, $x$"Sober" is a fact about you, not the name of you. The identity trap in both directions — the drinker identity ("I'm just a guy who parties") and the recovery-only identity (where sobriety becomes the entire personality). Every module you've done was a vote for someone — the person who walks off cravings, maps their triggers, tells the truth. That's who's being built.$x$, $x$The Becoming Statement, sobriety edition: "I'm becoming someone who ______" — built from your own last 13 modules, written, kept.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_sobriety', 14, 4, $x$BECOME IT$x$, $x$The Long Game$x$, $x$What months 2, 6, and 12 actually look like (the pink cloud, the wall, the ordinary Tuesday when you realize you didn't think about it all day). Milestones worth marking and how to mark them (the 30-day ritual: do something your old routine made impossible — the Saturday morning hike, the clear-headed call). The maintenance kit: which KEEPs stay in the pocket forever (Modules 4 and 8), the map that keeps updating (5), the ritual that keeps evolving (7).$x$, $x$Put your 30-day marker on the calendar — the date and the thing you'll do. Then leave a note for the person who'll read this program again on a hard day: one sentence, from you, to you.$x$, NULL, NULL, NULL, $x$This program is education and support, not medical treatment. If you drink heavily every day, talk to a doctor before stopping suddenly — withdrawal can be dangerous. In crisis, help comes first: 988 (US) or your local emergency number.$x$),
('prog_grief', 1, 1, $x$WHAT GRIEF ACTUALLY IS$x$, $x$There's No Wrong Way$x$, $x$The myths, dismantled: the five stages were never a checklist (Kübler-Ross wrote about the dying, not the grieving, and never meant them as a sequence); there is no timeline; "strong" doesn't mean dry-eyed; grief that comes in waves isn't grief done wrong. What grief actually is: love with nowhere to put itself, and a nervous system doing exactly what it's built to do.$x$, $x$Write one sentence: "What I lost was ______." (A person, a marriage, a version of the future — all count. This sentence is the anchor for everything after.)$x$, NULL, NULL, $x$Riley layer: Riley holds this sentence permanently and never makes the person repeat it.$x$, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 2, 1, $x$WHAT GRIEF ACTUALLY IS$x$, $x$What's Happening in Your Body$x$, $x$Grief is physical. The exhaustion that sleep doesn't fix, the brain fog (grief measurably impairs memory and concentration — you're not losing it), the appetite that vanished or doubled, the chest-heaviness with a medical name (takotsubo is real, if rare). Why: your body is running a threat response around the clock. What helps isn't thinking harder — it's the boring trinity: water, food, walking. (The 8:14 Reset pairs here.)$x$, $x$Pick ONE body-basic to protect this week — a real meal a day, a ten-minute walk, a bedtime. One. Guard it.$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 3, 1, $x$WHAT GRIEF ACTUALLY IS$x$, $x$The Daily Grief Check-In$x$, $x$Grief unattended leaks into everything; grief given a daily appointment becomes carryable. The check-in isn't wallowing — it's containment with a door, not a wall.$x$, $x$Do the first one now. Set the daily time.$x$, $x$The Daily Grief Check-In$x$, $x$**THE CHECK-IN (2 minutes, once a day, same time if possible):**
1. **Weather report:** Today my grief is ______ (a fog / a wave / a stone / quiet / loud). No fixing — naming.
2. **The body scan:** Where is it sitting right now? (Chest, throat, shoulders, nowhere.)
3. **One memory OR one mercy:** Either one true memory of what was lost — even a hard one — or one thing that made today slightly more livable. Grief days get one or the other; both is a good day.
4. **The door closes:** "I'll come back tomorrow." Said or written. This is what makes it a practice and not a flood.$x$, $x$Riley layer (Coach): the check-in becomes a Riley conversation; Riley tracks the weather reports over weeks and can gently show the person their own pattern — "more quiet days lately than fog days."$x$, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 4, 1, $x$WHAT GRIEF ACTUALLY IS$x$, $x$Waves and Ambushes$x$, $x$The grocery-store moment — their brand on the shelf, a song, a smell, a handwriting sample — and you're leveled at 2pm on a Tuesday. Grief bursts are normal, neurological, and time-limited (they crest and pass, like all waves — minutes, not days). The Ambush Protocol: stop pretending you're fine; hand on chest; name it ("this is a wave, it will pass"); breathe out longer than in; let it finish. Ambushes are not setbacks — they're evidence the love was load-bearing.$x$, $x$Write your three likeliest ambush triggers. Not to avoid them — to un-surprise them.$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 5, 2, $x$CARRYING IT DAILY$x$, $x$The Firsts$x$, $x$The first birthday, first holiday, first anniversary of the day itself — the calendar becomes a minefield the first year. The planning principle: firsts hurt less when they're decided in advance (attend / skip / replace with something new) — any choice beats being ambushed by a date. Include the anticipation warning: the days *before* a first are often worse than the day. And permission, in writing: you're allowed to skip the holiday. You're allowed to change every tradition. You're allowed to keep them all.$x$, $x$The Firsts Map — list the next three coming dates, and decide now: attend, adapt, or skip. Tell one person the plan.$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 6, 2, $x$CARRYING IT DAILY$x$, $x$When Grief Gets Complicated$x$, $x$Some griefs tangle: sudden loss, overdose, suicide, the death of someone you were in conflict with, the loss you saw coming for years that flattened you anyway. What "complicated grief" (prolonged grief) actually means clinically — and the honest line: this program helps carry; if a year in the grief still runs the whole day, every day, a grief-trained therapist isn't failure, it's the right tool. How to find one (psychology-today-style directories, "grief" and "prolonged grief" as search filters, group options like GriefShare or The Compassionate Friends for child loss, survivor-of-suicide groups).$x$, $x$No action today except this: if the paragraph above described you, write down one therapy or group option to look up. That's the whole module's ask.$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 7, 2, $x$CARRYING IT DAILY$x$, $x$Grief That Isn't Death$x$, $x$Disenfranchised grief — the losses the world doesn't send casseroles for: divorce, estrangement, a diagnosis that ended a future, a friendship's death, a job that was an identity, the child you didn't have, the parent still alive but no longer *them* (anticipatory and ambiguous loss). It's all grief. Same waves, same body, same tools — with an extra weight: nobody's acknowledging it. Step one is you acknowledging it (Module 1's sentence already did).$x$, $x$Rewrite Module 1's sentence if it was hiding a non-death loss behind a politer one. Then tell ONE safe person: "I'm actually grieving ______."$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 8, 2, $x$CARRYING IT DAILY$x$, $x$The Divorce Chapter$x$, $x$A dedicated room for the most common non-death loss. Divorce grief is grief plus paperwork plus an ex who still exists plus a jury of opinions. The identity unwind ("we" for fifteen years — who's "I"?); grieving the future you'd planned more than the person; kids and the discipline of not grieving *at* them; the ex you have to keep co-parenting with (boundaries as grief hygiene); the friend-group split. And the unspeakable one, spoken: relief is allowed. Relief and grief share a bed constantly.$x$, $x$Two lists, five items each: "What I actually lost" / "What I actually didn't." Read the second one twice.$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 9, 2, $x$CARRYING IT DAILY$x$, $x$Guilt, Anger, Relief (The Feelings Nobody Admits)$x$, $x$The unspoken three. Guilt — the last conversation, the missed call, the "I should have known" (hindsight is a liar; you decided with the information you had). Anger — at them for leaving, at the doctors, at God, at people whose lives kept going; anger is grief with adrenaline, and it's allowed. Relief — after long caregiving, after addiction, after a hard relationship: relief is not betrayal; it's the nervous system finally exhaling, and it can hold hands with devastation.$x$, $x$Which of the three lives in you? Write it the letter it's been waiting to send. Nobody reads it. Burning it after is allowed and traditional.$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 10, 3, $x$THE PEOPLE AROUND YOU$x$, $x$The Family Companion Guide$x$, $x$The people who love you are guessing, and mostly guessing wrong. This module is written to be handed to them.$x$, $x$Send or hand the guide to one person. (In-app: shareable link/PDF — this is also the program's most natural organic-growth loop.)$x$, $x$The Family Companion Guide$x$, $x$**THE GUIDE (a printable page addressed to the griever's people):**
- Say the name. You won't remind them — they never forgot. Silence is what hurts.
- Don't rank the loss ("at least..."). Every sentence starting with "at least" should end before it starts.
- Specific beats general: not "let me know if you need anything" but "I'm bringing dinner Thursday — door or doorstep?"
- The second month matters more than the first week. Calendar a check-in for when the casseroles stop.
- Let them repeat the story. Retelling is how the brain files it. The tenth telling counts like the first.
- Don't flinch at tears; don't force them either. Your only job is to stay in the room.
- Grief has no deadline. "Still?" is not a question that helps. Yes, still.$x$, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 11, 3, $x$THE PEOPLE AROUND YOU$x$, $x$Boundaries for the Grieving$x$, $x$The comment section of your loss: the platitude people ("everything happens for a reason"), the grief police ("shouldn't you be over this?"), the vampires who feed on proximity to tragedy. Scripts, word for word: the deflect ("we're doing the best we can, thanks for asking"), the boundary ("I'm not able to talk about the details"), the exit ("I need to step out — nothing personal"). You owe your grief to no one. Protecting it is not rudeness; it's triage.$x$, $x$Pick your top offender and pre-load your script. Say it out loud once.$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 12, 4, $x$LIVING FORWARD$x$, $x$Keeping Them With You$x$, $x$The goal was never letting go — the research calls it continuing bonds, and it's the healthy norm across most of human history and culture. Rituals that carry: the object worn or carried (a watch, say — set to a moment that mattered), the meal cooked on their day, the work done in their name, the conversation you keep having with them (out loud in the car is normal; most grievers do it and few admit it). The bond doesn't end; it changes address.$x$, $x$Choose or name your carrying ritual — one object, date, or practice. If one already exists (it usually does), make it official: that's the ritual now.$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 13, 4, $x$LIVING FORWARD$x$, $x$Joy Without Betrayal$x$, $x$The first real laugh after — and the guilt that arrives one second later. The lie underneath: that joy measures forgetting, that staying miserable is staying loyal. The truth: your joy was what they built, contributed to, or wanted; it's their work still running. Grief and joy are not on a see-saw — they ride in the same chest, same day, same hour. Permission, in writing: laugh at the funeral story. Enjoy the vacation. Fall in love again, if that's your road. Loyalty was never measured in suffering.$x$, $x$Do one thing this week you'd have enjoyed *before* — and when the guilt shows up on schedule, say (out loud): "This doesn't mean I've forgotten. It means I'm carrying it well."$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_grief', 14, 4, $x$LIVING FORWARD$x$, $x$Living Forward$x$, $x$Not "moving on" — moving *with*. The load never reaches zero; you grow around it (the "growing around grief" model — the grief stays the same size; the life grows bigger around it). What month 12 and year 3 can look like: the weather reports trend quieter; the ambushes space out; the person becomes less a wound and more a companion. The maintenance kit: the Daily Check-In (Module 3) stays, dialed down to when-needed; the Firsts Map (5) gets renewed each year; the Companion Guide (10) gets handed to each new person who matters. And the Becoming Statement, grief edition: *"I'm becoming someone who carries ______ — and still ______."*$x$, $x$Write the statement. Both blanks. Keep it with Module 1's sentence — first page and last page of the same story.$x$, NULL, NULL, NULL, $x$This program is companionship and education, not therapy. If grief has you thinking about not wanting to be here, that needs a human, now: 988 (US) or your local crisis line. Riley — and this program — will always point you to real help first.$x$),
('prog_body', 1, 1, $x$START LOW$x$, $x$The Deal$x$, $x$What this is and isn't. No transformation-porn, no 75-day gauntlets, no earning your worth in mirror selfies. The rebuild order is fixed and non-negotiable: energy → strength → everything else. Why the fitness industry's front door (intensity) is backwards for a depleted person, and why ten minutes done beats sixty minutes planned. The only metric that matters for the first month: *did you show up at all.*$x$, $x$Write your actual why in one sentence — not the "should" why. ("Keep up with my kids" beats "lose 20 lbs." "Stop feeling 70 at 45" beats both.)$x$, NULL, NULL, $x$Riley layer: Riley keeps the why and returns it verbatim on the first bad week.$x$, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 2, 1, $x$START LOW$x$, $x$Where You Are (The No-Shame Baseline)$x$, $x$You can't route a map without a starting pin — but the pin is data, not a verdict. The four-question baseline (no scale required): (1) Flights of stairs before you're breathing hard? (2) Can you get up off the floor without hands? (3) Hours of real sleep? (4) Energy at 3pm, 1–10? That's it. The mirror-voice section: the audit is of capacity, never of appearance — per the house rules, nothing in this program ever talks about your body the way you wouldn't let someone talk to a friend.$x$, $x$Answer the four questions. Date them. You'll answer them again at Module 14.$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 3, 2, $x$MOVE$x$, $x$The 10-Minute Start$x$, $x$Why ten minutes: it's under the excuse threshold, over the effect threshold (mood lift and blood-sugar effect are real at this dose), and repeatable on your worst day.
**WORKOUT A — THE START (10 min, no equipment, written for a hallway and a wall):**
- 2 min — walk (hallway laps count) or march in place
- 1 min — wall push-ups, your pace, rest whenever
- 1 min — sit-to-stand from a chair (the single most life-extending exercise nobody respects)
- 1 min — walk / recover
- 1 min — wall push-ups again
- 1 min — sit-to-stands again
- 2 min — walk
- 1 min — stretch anything that's talking to you
Every element scales down (wall angle, chair height, pace) — the floor version of this workout is *sitting down and standing up during commercials.* That version counts.$x$, $x$Do Workout A once. Not well. Once.$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 4, 2, $x$MOVE$x$, $x$The 8-Minute Reset Workout$x$, $x$For the moment the wave hits — craving, rage, panic, the 3pm despair — movement is the fastest state-change chemistry legally available. Pre-decided, so the deciding is already done. (Sobriety program owners will recognize this as Step 2 of the Emergency Craving Protocol — same tool, same 8 minutes, on purpose. And yes: 8 minutes — the watch again.)$x$, $x$Save it where the Craving Protocol lives. Run it once today *without* needing it, so your body knows the route.$x$, $x$The 8-Minute Reset Workout$x$, $x$**THE 8-MINUTE RESET (no equipment, anywhere, even a parking lot):**
- Minute 1 — fast walk or stair climb, harder than comfortable
- Minute 2 — wall or counter push-ups to fatigue, then hold the top
- Minute 3 — sit-to-stands or air squats, steady
- Minute 4 — fast walk again
- Minute 5 — the carry: anything heavy (backpack, jug, toddler), walked
- Minute 6 — squats or stairs again
- Minute 7 — slow walk, breathe out longer than in
- Minute 8 — stand still. Hand on chest. Notice: different chemistry than 8 minutes ago.$x$, $x$Riley layer (Coach): "I'm spiraling / craving / furious" in chat → Riley offers to run the 8 minutes live, minute by minute.$x$, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 5, 2, $x$MOVE$x$, $x$The Ladder (Weeks, Not Willpower)$x$, $x$Progression that respects a rebuild: 10 minutes → 15 → 20, adding one rung only after the current one feels boring (boredom, not suffering, is the promotion signal). Workouts B and C provided as templates: **B (15 min)** adds a floor row (towel + door) or backpack rows, incline push-ups (counter → chair as they get stronger), and a longer walk block; **C (20 min)** adds step-ups, backpack squats, and a farmer's carry. Three sessions a week is the whole ask. A missed week means repeat the rung, never restart the ladder.$x$, $x$Schedule three sessions this week — actual calendar entries, ten minutes each. Attendance is the metric.$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 6, 2, $x$MOVE$x$, $x$The Morning Ritual$x$, $x$The 8:14 morning — borrowed straight from the Reset and made permanent: light (outside or a window, 2 min), water (the glass you staged last night), movement (2 minutes of anything — stretching in the kitchen counts). Why the first ten minutes of the day punch so far above their weight: circadian anchoring, cortisol timing, and the psychological fact that a day that starts with one kept promise tends to keep more of them.$x$, $x$Stage tonight: glass by the bed, shoes by the door. Run the ritual tomorrow. That's it.$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 7, 3, $x$EAT$x$, $x$Blood Sugar Is Running Your Mood$x$, $x$The 3pm crash, the 9pm raid, the morning fog — mostly one mechanism: the spike-crash cycle, and how it impersonates depression, cravings, and personality flaws. The fix is boring and total: protein anchors, real food most of the time, and never fixing a crash with the thing that causes the next one. (Sobriety readers: this is Module 3's "blood sugar impersonating cravings," expanded.)$x$, $x$Tomorrow, one experiment: protein at breakfast, then note your 3pm on a 1–10. One data point. Most people feel this one immediately.$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 8, 3, $x$EAT$x$, $x$The 5 Rebuild Foods$x$, $x$Not a diet — a shortlist. Five foods that do disproportionate rebuild work, with zero exotic anything: (1) **Eggs** — the cheapest complete protein with its own packaging; (2) **Greek yogurt** — protein + gut repair in one container, no cooking; (3) **Oats** — steady-release fuel that ends the morning spike; (4) **Frozen vegetables** — nutritionally equal to fresh, zero prep guilt, never rot accusingly in the drawer; (5) **Canned beans/lentils** — protein + fiber for a dollar. The rule: these five live in the house at all times. Everything else is negotiable.$x$, $x$The next store run includes all five. Total cost: roughly one takeout order.$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 9, 3, $x$EAT$x$, $x$The Starter Plate$x$, $x$The only meal-construction rule in the whole program: **a protein + a vegetable + something whole.** No macros, no weighing, no apps. Assembly counts as cooking: rotisserie chicken + frozen broccoli + microwave rice is a perfect plate. Ten example plates provided, none requiring more than 12 minutes or 4 ingredients.$x$, $x$Build one Starter Plate today. Notice the hour-after (Module 7's experiment, repeated with dinner).$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 10, 3, $x$EAT$x$, $x$Batch Once, Eat All Week$x$, $x$The Sunday system — 60 minutes that deletes 15 food decisions from the week ahead. Decision fatigue, not knowledge, is why depleted people eat badly; this tool attacks the decisions, not the willpower.$x$, $x$Run the hour this week. Imperfectly. Three boxes instead of five still deletes nine decisions.$x$, $x$Batch Once, Eat All Week$x$, $x$**THE SYSTEM (60 min, once a week):**
1. **The shopping list (fixed template):** 2 proteins (one cooked-by-you: sheet-pan chicken thighs or a pot of ground beef; one ready-made: rotisserie, canned tuna, eggs) · 3 vegetables (2 frozen, 1 fresh) · 2 wholes (rice cooked in a pot, potatoes, bread) · the 5 Rebuild Foods restocked · 2 grab-items (yogurts, fruit, jerky) — the anti-vending-machine clause.
2. **The hour:** oven on → protein in → rice/potatoes going → while they cook, portion into 4–5 containers (protein + veg + whole per box) → done. Music or a show mandatory; suffering is not part of the system.
3. **The week:** lunch is a box. Dinner is a box or a Starter Plate. The 9pm raid finds yogurt standing guard.$x$, $x$Riley layer (Coach): the shopping list regenerates weekly, adapted to what the person actually ate and reported — this module is the Nutrition Engine's on-ramp.$x$, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 11, 3, $x$EAT$x$, $x$28 Meals That Assemble Themselves$x$, $x$The reference library — 28 meal concepts (7 breakfasts, 7 lunches, 7 dinners, 7 "it's 9pm and I'm human" snacks), every one buildable from the Module 8 + 10 shopping pattern, none over 15 minutes. Breakfasts lead with protein (Module 7); dinners are all Starter Plates in costume; the snack list is engineered to out-compete the pantry's worst offers. (Full 28 written as the in-app content set — each: name, 3–5 ingredients, assembly line, minutes.)$x$, $x$Star seven — one per day next week. The week plans itself.$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 12, 4, $x$KEEP GOING$x$, $x$Sleep Is Training$x$, $x$The rebuild happens at night — muscle, mood, and blood sugar are all repaired on the pillow, and one short night measurably wrecks the next day's food choices and willpower. The 8:14 Wind-Down (from the Reset) made permanent: caffeine cutoff, phone across the room, one orderly square. Plus the rebuild-specific additions: consistent wake time beats consistent bedtime; the 20-minute rule for lying awake (get up, boring activity, return).$x$, $x$Pick your caffeine cutoff and your wake time. Two decisions, tonight, both allowed to be imperfect.$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 13, 4, $x$KEEP GOING$x$, $x$Bad Weeks (The Floor Protocol)$x$, $x$The week the wheels come off — sick kid, work explosion, grief wave, relapse, life. The all-or-nothing trap is the actual program-killer: nobody quits from a bad workout; they quit from the story that one bad week means it's over. **THE FLOOR:** the pre-decided minimum that keeps the identity alive when everything else pauses — one 10-minute session OR three morning rituals OR one batch hour. Any one. That's a maintained week, officially. The restart is always the ladder rung you left, never rung one.$x$, $x$Write your floor now, in a good week, and put it where the KEEPs live. (Per the house rules: the fallback is always smaller, never sterner.)$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$),
('prog_body', 14, 4, $x$KEEP GOING$x$, $x$The Body You Live In$x$, $x$Re-answer Module 2's four questions; put the two dated answers side by side — stairs, floor, sleep, 3pm. That delta is the program. The identity close: strength as self-respect, not appearance — every session was a vote for someone who shows up for their own body, and that person now exists on the record. The Becoming Statement, body edition: *"I'm becoming someone whose body can ______."* And the one-time honest note: if you want the plans to start adapting to you — workouts that adjust to your week, a shopping list that learns what you eat — that's what Riley Coach does. This program is the on-ramp; it's also complete on its own. Both are true.$x$, $x$Write the statement next to your Module 1 why. First page and last page, same story.$x$, NULL, NULL, NULL, $x$This program is general fitness and nutrition education, not medical advice. New to exercise, pregnant, managing a condition, or on medications that affect blood sugar? Check with your doctor first. Pain (sharp, not sore) means stop.$x$);
